#python cli package manager

##where pip looks for packages

#pypi is the main repository: <https://pypi.python.org/pypi>

#ubuntu install:

    sudo aptitude install -y python-pip
    sudo pip install --upgrade pip 

#install virtualenv:

    sudo pip install --upgrade virtualenv

#it allows you to run programs in a virtual envirnoment,
#that is, in which you control the versions of all dependencies
#such as modules.

#search package:

    pip search $pkg

#install package:

    sudo pip install $pkg

#list installed packages on stdout:

    pip freeze

#install packages listed on a pip file:

    pip install -r requirements.pip

#a pip files is just a newline separated list of filenames
#the format is exactly the same generated by pip freeze

#uninstall package:

    sudo pip uninstall $pkg
