# Python CLI package manager.

# Not part of the stdlib (yet!).

# Manages package dependencies.

# pip looks by default for packages under pypi (aka the cheeseshop)
# located at: <https://pypi.python.org/pypi>

# It is also possible to add custom servers,
# and even to install from source control protocols such as git directly.

# Search for a package:

    pip search $pkg

# Install package:

    sudo pip install $pkg

# List installed packages with versions to stdout:

    pip freeze

# Install packages listed on a pip file:

    pip install -r requirements.pip

# Install from git repo:

# TODO get this working

    sudo pip install git+git@github.com:cirosantilli/python.git@head

# .pip files is just a newline separated list of filenames
# the format is exactly the same generated by pip freeze

# Show all files of installed package:

    pip show -f $pkg

# Uninstall package:

    sudo pip uninstall $pkg
