#!/usr/bin/env bash
set -eux
find . -name '*.pyc' -delete
find . -name __pycache__ -prune -exec rm -r "{}" \;
python2 main.py
find . -name '*.pyc' -delete
find . -name __pycache__ -prune -exec rm -r "{}" \;
python3 main.py
